# Generated by Django 3.1.5 on 2022-06-24 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('deadline', models.DateField(default=None, null=True)),
                ('type', models.CharField(default=None, max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('last_modified_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User2Taskboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(default=None, max_length=10)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('last_modified_dt', models.DateTimeField(auto_now=True)),
                ('taskboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskboardId', to='taskboard.taskboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
