# Generated by Django 3.1.5 on 2022-06-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0002_taskboard_user2taskboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2taskboard',
            name='taskboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskboardId', related_query_name='user2taskboard', to='taskboard.taskboard'),
        ),
    ]
