# Generated by Django 3.1.5 on 2022-07-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0003_auto_20220626_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskboard',
            name='delete_ind',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='user2taskboard',
            name='delete_ind',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
