# Generated by Django 3.1.5 on 2022-07-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0004_auto_20220702_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskboard',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Taskboard_created_by', to='taskboard.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskboard',
            name='last_modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='askboard_last_modified_by', to='taskboard.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user2taskboard',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User2Taskboard_created_by', to='taskboard.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user2taskboard',
            name='last_modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User2Taskboard_last_modified_by', to='taskboard.user'),
            preserve_default=False,
        ),
    ]
