# Generated by Django 3.1.5 on 2022-07-22 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0006_remove_taskboard_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('last_modified_dt', models.DateTimeField(auto_now=True)),
                ('delete_ind', models.CharField(default='F', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Section_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Section_last_modified_by', to=settings.AUTH_USER_MODEL)),
                ('taskboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskboardForSection', related_query_name='taskboardForSection', to='taskboard.taskboard')),
            ],
        ),
    ]
