# Generated by Django 3.1.5 on 2022-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0008_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_ind',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
