USER_ROLE_OWNER = "OWNER"
USER_ROLE_MEMBER = "MEMBER"
USER_ROLE_REMOVED = "REMOVED"

TASKBOARD_TYPE_GRP = "GRP"
TASKBOARD_TYPE_IND = "IND"

DELETE_IND_T = "T"
DELETE_IND_F = "F"

NEW_OWNER_EMPTY = "NEW_OWNER_EMPTY"